pages:
  - name: Lucario ETB
    url: https://www.target.com/p/pok--233-mon-trading-card-game--mega-evolution-elite-trainer-box--lucario--no-aasa/-/A-94681776
    viewport: [1440, 2000]
    wait_for: body
    mask:
      - ".ad"
      - "#timestamp"

  - name: Lucario Price
    url: https://www.target.com/p/pok--233-mon-trading-card-game--mega-evolution-elite-trainer-box--lucario--no-aasa/-/A-94681776
    viewport: [1440, 2200]
    wait_for: body
    mask: []
